/****************************************************************************************
 * File Name    : CMP_ITriggerHandler
 * Author       : sy.lee
 * Date         : 2023-07-25
 * Description  :
 * Copyright (c) 2023. LG CNS, All Rights Reserved.
 * Modification Log
 * ===============================================================
 * Ver      Date 		Author    			Modification
 * ===============================================================
   1.0		2023-07-25 	sy.lee			    Create

****************************************************************************************/
public interface CMP_ITriggerHandler {
    void run();
}